stripetest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('admin/', admin.site.urls),
	path('subscriptions/', include('subscriptions.urls', namespace='subscriptions')),
]

subscriptions/urls.py
from django.urls import path

from .views import (
	MembershipSelectView, 
	PaymentView, 
	updateTransactionRecords,
	cancelSubscription
	)

app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactionRecords, name='update-transactions'),
    path('cancel/', cancelSubscription, name='cancel')
]

subscriptions/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save


from datetime import datetime
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
	('Expert', 'exp'),
	('Basic', 'bas'),
	('Free', 'free')
)

class Membership(models.Model):
	slug = models.SlugField()
	membership_type = models.CharField(
			choices=MEMBERSHIP_CHOICES,
			default='Free',
			max_length=30)
	price = models.IntegerField(default=15)
	stripe_plan_id = models.CharField(max_length=40)

	def __str__(self):
		return self.membership_type


class UserMembership(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	stripe_customer_id = models.CharField(max_length=40)
	membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
	if created:
		UserMembership.objects.get_or_create(user=instance)

	user_membership, created = UserMembership.objects.get_or_create(user=instance)

	if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
		new_customer_id = stripe.Customer.create(email=instance.email)
		user_membership.stripe_customer_id = new_customer_id['id']
		user_membership.save()

post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)


class Subscription(models.Model):
	user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
	stripe_customer_id = models.CharField(max_length=40)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.user_membership.user.username

	@property
	def get_created_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.created)

	@property
	def get_next_billing_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.current_period_end)

subscriptions/views.py
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.urls import reverse


from .models import Membership, UserMembership, Subscription

import stripe



def get_user_membership(request):
	user_membership_qs = UserMembership.objects.filter(user=request.user)
	if user_membership_qs.exists():
		return user_membership_qs.first()
	return None

def get_user_subscription(request):
	user_subscription_qs = Subscription.objects.filter(
			user_membership=get_user_membership(request))
	if user_subscription_qs.exists():
		user_subscription = user_subscription_qs.first()
		return user_subscription
	return None

def get_selected_membership(request):
	membership_type = request.session['selected_membership_type']
	selected_membership_qs = Membership.objects.filter(
				membership_type=membership_type)
	if selected_membership_qs.exists():
		return selected_membership_qs.first()
	return None


class MembershipSelectView(ListView):
	model = Membership

	# def get_context_data(self, *args, **kwargs):
	# 	context = super().get_context_data(**kwargs)
	# 	current_membership = get_user_membership(request)
	# 	context['current_membership'] = str(current_membership.membership)
	# 	return context

	def post(self, request, **kwargs):
		user_membership = get_user_membership(request)
		user_subscription = get_user_subscription(request)

		selected_membership_type = request.POST.get('membership_type')

		selected_membership_qs = Membership.objects.filter(
				membership_type=selected_membership_type)
		print(selected_membership_qs)
		selected_membership = selected_membership_qs.first()
		print(selected_membership)
		'''
		==========
		VALIDATION
		==========
		'''

		if user_membership.membership == selected_membership:
			if user_subscription != None:
				messages.info(request, "You already have this membership. Your \
					next payment is due {}".format('get this value from stripe'))
				return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		# assign to the session
		request.session['selected_membership_type'] = selected_membership.membership_type

		return HttpResponseRedirect(reverse('memberships:payment'))



def PaymentView(request):

	user_membership = get_user_membership(request)

	selected_membership = get_selected_membership(request)

	publishKey = settings.STRIPE_PUBLISHABLE_KEY

	if request.method == "POST":
		try:
			token = request.POST['stripeToken']
			subscription = stripe.Subscription.create(
			  customer=user_membership.stripe_customer_id,
			  items=[
			    {
			      "plan": selected_membership.stripe_plan_id,
			    },
			  ],
			  source=token # 4242424242424242
			)

			return redirect(reverse('memberships:update-transactions',
				kwargs={
					'subscription_id': subscription.id
				}))

		except stripe.CardError as e:
			messages.info(request, "Your card has been declined")

	context = {
		'publishKey': publishKey,
		'selected_membership': selected_membership
	}

	return render(request, "memberships/membership_payment.html", context)


def updateTransactionRecords(request, subscription_id):
	user_membership = get_user_membership(request)
	selected_membership = get_selected_membership(request)

	user_membership.membership = selected_membership
	user_membership.save()

	sub, created = Subscription.objects.get_or_create(user_membership=user_membership)
	sub.stripe_subscription_id = subscription_id
	sub.active = True
	sub.save()

	try:
		del request.session['selected_membership_type']
	except:
		pass

	messages.info(request, 'Successfully created {} membership'.format(selected_membership))
	return redirect('/memberships')


def cancelSubscription(request):
	user_sub = get_user_subscription(request)

	if user_sub.active == False:
		messages.info(request, "You dont have an active membership")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
	sub.delete()

	user_sub.active = False
	user_sub.save()


	free_membership = Membership.objects.filter(membership_type='Free').first()
	user_membership = get_user_membership(request)
	user_membership.membership = free_membership
	user_membership.save()

	messages.info(request, "Successfully cancelled membership. We have sent an email")
	# sending an email here

	return redirect('/memberships')

subscriptions/templates/subscriptions/membership_list.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
	<h1>Select a membership</h1>
	<div class="row">
		{% for object in object_list %}
		<div class="col-sm-4 col-md-4">
			<h2>{{ object.membership_type }}</h2>
			<p>Price: ${{ object.price }}<small>/month</small></p>
			<ul>
				
			</ul>
			{% if object.membership_type != 'Free' %}
			<form method="POST" action="{% url 'memberships:select' %}">
				{% csrf_token %}
				{% if object.membership_type != current_membership %}
					<button class="btn btn-warning">Select</button>
				{% else %}
					<small>This is your current membership</small>
				{% endif %}
				<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
			</form>			
			{% endif %}	
		</div>
		{% endfor %}
	</div>
</div>



{% endblock content %}

subscriptions/templates/subscriptions/profile.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
	<div class="row">
		<h1>My Profile</h1>
		<div class="col-sm-4 col-md-4">
			{% if user_subscription != None %}
				<h4>Current Membership: {{ user_membership.membership.membership_type }} <small>since {{ user_subscription.get_created_date }}</small></h4>

				{% if user_subscription.active != False %}
					<a href="{% url 'memberships:cancel' %}">Cancel subscription</a>

				{% else %}
					<p>You don't have an active membership plan. Check them out here 
						<a href="{% url 'memberships:select' %}"></a>
					</p>
				{% endif %}
			{% endif %}
		</div>
	</div>
</div>	
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>


	{% block content %}
	{% endblock content %}

	<script
  	src="https://code.jquery.com/jquery-3.3.1.js"
  	integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  	crossorigin="anonymous"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>